### ISSUE TITLE
Project does not compile

### ISSUE THREAD

**Issue by Zammy** [DreamersIncStudios/ECS-IAUS-sytstem#56]
Hello,

I checkout branch `Stable-0.7.2-2020LTS` and it does not compile. I openned it with unity version pointed in `ProjectVersion.txt`. 

`Assets\Systems\InfluenceSystem\Faction Database\Relationship.cs(24,23): error CS0246: The type or namespace name 'Pool<>' could not be found (are you missing a using directive or an assembly reference?)`

If there are extra steps to make the project compile, can we add them to the readme?

-Evgeni

**Comment by DreamersIncStudios** [comment]
The project uses the paid asset love/hate by pixel crushers. The influence grid depends on faction database. 

 https://assetstore.unity.com/packages/tools/ai/love-hate-33063

I will update the Readme in the next push this weekend.  Looking at refqctor

**Comment by MagnificentS** [comment]
Hi, I bought the asset and i still have issues with influenceGridObject
![image](https://user-images.githubusercontent.com/8756646/212669040-e4ec7c31-1124-4010-bc4d-061f30061a87.png)

![image](https://user-images.githubusercontent.com/8756646/212668791-782520b2-f125-4f48-93d3-26a84753c85a.png)
![image](https://user-images.githubusercontent.com/8756646/212668850-593c079e-5726-46f4-ad60-1046d81b12b8.png)

**Comment by DreamersIncStudios** [comment]
I am going on off of memory and notes as I am working on the Entities 1.0 Updated Branch. 
Love/Hate asset file must be located inside of the influence system folder as the project uses assembly definitions. 
In the Entites 1.0 refactor, I am adding a Plugins folder on the root direction and Love/Hate has it own assembly definition.

**Comment by MagnificentS** [comment]
makes sense. I have never worked with assembly definitions before so I got very worried.

**Comment by MagnificentS** [comment]
These are the only issues left
![image](https://user-images.githubusercontent.com/8756646/212707360-8e05d2c4-c8b5-4e48-958c-cbdc2ba9f082.png)

**Comment by MagnificentS** [comment]
Solution get DotTween its free.

![image](https://user-images.githubusercontent.com/8756646/213174701-040c5684-48d2-448f-9ade-3aef465701c4.png)
I don't know what to do about this one

**Comment by DreamersIncStudios** [comment]
Based on review line 8 can be deleted as the name space is not being used in this script.
